name: lsc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  badges: ^3.1.2
  google_maps_flutter: ^2.5.3
  fluttertoast: ^8.2.4
  hive: ^2.2.3
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  geolocator: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/images/
